FROM python:3.12-slim

WORKDIR /app

COPY requirements.trainer.lock .

RUN python -m pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.trainer.lock

COPY src ./src
COPY scripts ./scripts

CMD ["python", "-m", "src.training.trainer"]
